name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]
        composer_flags: ['', '--prefer-lowest']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}
        extensions: xdebug

    - uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php_version }}
        args: ${{ matrix.composer_flags }}
        command: update

    - name: Run tests
      run: ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
      env:
          XDEBUG_MODE: coverage
